// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBudFST1nRdV9gAQFDOeeUmjbvH9BOdmDI',
    appId: '1:827137468402:web:30e7abcb48c1c3ca026d6b',
    messagingSenderId: '827137468402',
    projectId: 'absensi-380ac',
    authDomain: 'absensi-380ac.firebaseapp.com',
    storageBucket: 'absensi-380ac.appspot.com',
    measurementId: 'G-6K1FHEV8FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHsK_eJW9v0oHUPyyDM3Z9UjemZmo49sA',
    appId: '1:827137468402:android:7d1a6028edf0c306026d6b',
    messagingSenderId: '827137468402',
    projectId: 'absensi-380ac',
    storageBucket: 'absensi-380ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu-0PSHByzFOWFYnVWX-PwOllrGPwbdnI',
    appId: '1:827137468402:ios:437387a94c9c2626026d6b',
    messagingSenderId: '827137468402',
    projectId: 'absensi-380ac',
    storageBucket: 'absensi-380ac.appspot.com',
    iosClientId: '827137468402-ra2m6rfn1bavs1mhdaaok0p5o174ofri.apps.googleusercontent.com',
    iosBundleId: 'com.ahmad.absensi',
  );
}
